version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: radius
      POSTGRES_USER: raduser
      POSTGRES_PASSWORD: radpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - radius_network
    restart: unless-stopped

  freeradius:
    container_name: freeradius
    build: ./freeradius
    depends_on:
      - postgres
    environment:
      RADIUS_DB_HOST: postgres
      RADIUS_DB_USER: raduser
      RADIUS_DB_PASS: radpass
      RADIUS_DB_NAME: radius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - freeradius_config:/etc/freeradius/3.0
    networks:
      - radius_network
    restart: unless-stopped

  daloradius:
    container_name: daloradius
    build: ./daloradius
    depends_on:
      - freeradius
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: raduser
      DB_PASS: radpass
      DB_NAME: radius
    ports:
      - "80:80"
    volumes:
      - daloradius_config:/var/www/html/library
    networks:
      - radius_network
    restart: unless-stopped

  captive-portal:
    container_name: captive-portal
    build: ./captive-portal
    depends_on:
      - freeradius
    ports:
      - "3000:3000"
    networks:
      - radius_network
    restart: unless-stopped

volumes:
  postgres_data:
  freeradius_config:
  daloradius_config:

networks:
  radius_network:
    driver: bridge
